[features]
seeds = false

[programs.localnet]
clever_todo = "2og7BbvrvbPjVeuULsWXKggN6gHBSim82L3X4pciucQ7"

[programs.devnet]
clever_todo = "2og7BbvrvbPjVeuULsWXKggN6gHBSim82L3X4pciucQ7"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/john/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
